---
title: "tools::CRAN_packages_db"
format: html
editor: visual
---

## Another place to explore is the

June Choe submitted basis in discusssions: https://github.com/teunbrand/ggplot-extension-club/discussions/62#discussioncomment-11310830

```{r}
library(tidyverse)
```

```{r, eval = F}

pkgs <- as_tibble(tools::CRAN_package_db())
gg_pkgs <- pkgs %>% 
  mutate(
    ind_ggplot_depend_import_suggest = if_any(-Package, ~ str_detect(.x, "ggplot2")),
    ind_gg = str_detect(Package, "gg|GG"),
    ind_ggplot_in_description = str_detect(Description, "ggplot"),
    ind_extension_in_description = str_detect(Description, "exten") 
         ) %>%
  filter(ind_ggplot_depend_import_suggest, 
         ind_gg | ind_ggplot_in_description) %>% 
  mutate(ext_score = ind_gg + ind_ggplot_in_description + ind_extension_in_description)
                                      

  
gg_pkgs |>
  write_csv("tools_cran_package_db_gg_packages.csv")
```

```{r, results='asis', message=F, warning=F}
read_csv("tools_cran_package_db_gg_packages.csv") %>% 
  arrange(-ext_score) %>% 
  mutate(pd = paste0(row_number(), ". ", Package,"; Description: ", 
                     Description, "  **Probable Extension Score: ", 
                     ext_score, "**")) %>%
  pull(pd) %>% 
  paste(collapse = "\n\n\n") %>% 
  cat()
  

```


```{r}
read_csv("tools_cran_package_db_gg_packages.csv") |> 
  pull(URL) %>% 
  str_extract("github.com/.+?/") %>% 
  str_remove("github.com/") %>% 
  str_remove("/") %>% 
  unique() ->
user_from_repo

read_csv("tools_cran_package_db_gg_packages.csv") |> 
  pull(URL) %>% 
  str_extract("https://.+github.io") %>% 
  str_remove(".github.io") %>% 
  str_remove("https://") %>% 
  unique() ->
user_from_io

user_from_io 

```
